set_property SRC_FILE_INFO {cfile:c:/Users/ppochiraju2024/Desktop/CHOICE-PUF/CHOICE_design/CHOICE_design.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0/design_1_processing_system7_0_0_in_context.xdc rfile:../../../CHOICE_design.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0/design_1_processing_system7_0_0_in_context.xdc id:1 order:EARLY scoped_inst:design_1_i/processing_system7_0} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/ppochiraju2024/Desktop/CHOICE-PUF/hw_src/constraints/base_constraints.xdc rfile:../../../../hw_src/constraints/base_constraints.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/ppochiraju2024/Desktop/CHOICE-PUF/hw_src/constraints/PUF_constraints.xdc rfile:../../../../hw_src/constraints/PUF_constraints.xdc id:3} [current_design]
current_instance design_1_i/processing_system7_0
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports {}]
current_instance
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_pblock PUF_Block_Zone
resize_pblock [get_pblocks PUF_Block_Zone] -add {CLOCKREGION_X0Y1:CLOCKREGION_X0Y1}
set_property CONTAIN_ROUTING 1 [get_pblocks PUF_Block_Zone]
set_property EXCLUDE_PLACEMENT 1 [get_pblocks PUF_Block_Zone]
set_property IS_SOFT FALSE [get_pblocks PUF_Block_Zone]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
add_cells_to_pblock [get_pblocks PUF_Block_Zone] [get_cells -hierarchical -regexp {GEN_PUF\[.*\].PUF/.*}]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V5 [get_ports clk]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U7 [get_ports ff_reset]
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ff_reset]
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V7 [get_ports chip_enable]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports chip_enable]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T9 [get_ports ASR_data_conf[0]]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U10 [get_ports ASR_data_conf[1]]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ASR_data_conf[*]]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y7 [get_ports ASR_length_conf[0]]
set_property src_info {type:XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y6 [get_ports ASR_length_conf[1]]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ASR_length_conf[*]]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y9 [get_ports puf_response[0]]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y8 [get_ports puf_response[1]]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W8 [get_ports puf_response[2]]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W10 [get_ports puf_response[3]]
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports puf_response[*]]
set_property src_info {type:XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X28Y100 [get_cells {GEN_PUF[9].PUF/CARRY4_inst}]
set_property src_info {type:XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X40Y100 [get_cells {GEN_PUF[15].PUF/CARRY4_inst}]
set_property src_info {type:XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X44Y100 [get_cells {GEN_PUF[17].PUF/CARRY4_inst}]
set_property src_info {type:XDC file:3 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X48Y100 [get_cells {GEN_PUF[19].PUF/CARRY4_inst}]
set_property src_info {type:XDC file:3 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X52Y100 [get_cells {GEN_PUF[21].PUF/CARRY4_inst}]
set_property src_info {type:XDC file:3 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X56Y100 [get_cells {GEN_PUF[23].PUF/CARRY4_inst}]
set_property src_info {type:XDC file:3 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X60Y100 [get_cells {GEN_PUF[25].PUF/CARRY4_inst}]
set_property src_info {type:XDC file:3 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y100 [get_cells {GEN_PUF[27].PUF/CARRY4_inst}]
set_property src_info {type:XDC file:3 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[0].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[0].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[0].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[0].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[0].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[1].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[1].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[1].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[1].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[1].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[2].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[2].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[2].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[2].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[2].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[3].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[3].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[3].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[3].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[3].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[4].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[4].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[4].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[4].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[4].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[5].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[5].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[5].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[5].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[5].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[6].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[6].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[6].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[6].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[6].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[7].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[7].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[7].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[7].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[7].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X26Y100 [get_cells -hierarchical -regexp {GEN_PUF\[8\]\.PUF/SRLC32E_inst_.*}]
set_property src_info {type:XDC file:3 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[8].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[8].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[8].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[8].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X26Y100 [get_cells {GEN_PUF[8].PUF/CARRY4_inst}]
set_property src_info {type:XDC file:3 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[8].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X26Y100 [get_cells {GEN_PUF[8].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[9].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[9].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[9].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[9].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[9].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X28Y100 [get_cells {GEN_PUF[9].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X30Y100 [get_cells -hierarchical -regexp {GEN_PUF\[10\]\.PUF/SRLC32E_inst_.*}]
set_property src_info {type:XDC file:3 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[10].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[10].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[10].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[10].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X30Y100 [get_cells {GEN_PUF[10].PUF/CARRY4_inst}]
set_property src_info {type:XDC file:3 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[10].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X30Y100 [get_cells {GEN_PUF[10].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X32Y100 [get_cells -hierarchical -regexp {GEN_PUF\[11\]\.PUF/SRLC32E_inst_.*}]
set_property src_info {type:XDC file:3 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[11].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[11].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[11].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[11].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X32Y100 [get_cells {GEN_PUF[11].PUF/CARRY4_inst}]
set_property src_info {type:XDC file:3 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[11].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X32Y100 [get_cells {GEN_PUF[11].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X34Y100 [get_cells -hierarchical -regexp {GEN_PUF\[12\]\.PUF/SRLC32E_inst_.*}]
set_property src_info {type:XDC file:3 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[12].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[12].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[12].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[12].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X34Y100 [get_cells {GEN_PUF[12].PUF/CARRY4_inst}]
set_property src_info {type:XDC file:3 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[12].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X34Y100 [get_cells {GEN_PUF[12].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y100 [get_cells -hierarchical -regexp {GEN_PUF\[13\]\.PUF/SRLC32E_inst_.*}]
set_property src_info {type:XDC file:3 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[13].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[13].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[13].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[13].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y100 [get_cells {GEN_PUF[13].PUF/CARRY4_inst}]
set_property src_info {type:XDC file:3 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[13].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y100 [get_cells {GEN_PUF[13].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X38Y100 [get_cells -hierarchical -regexp {GEN_PUF\[14\]\.PUF/SRLC32E_inst_.*}]
set_property src_info {type:XDC file:3 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[14].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[14].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[14].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[14].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X38Y100 [get_cells {GEN_PUF[14].PUF/CARRY4_inst}]
set_property src_info {type:XDC file:3 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[14].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X38Y100 [get_cells {GEN_PUF[14].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[15].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[15].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[15].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[15].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[15].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X40Y100 [get_cells {GEN_PUF[15].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X42Y100 [get_cells -hierarchical -regexp {GEN_PUF\[16\]\.PUF/SRLC32E_inst_.*}]
set_property src_info {type:XDC file:3 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[16].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[16].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[16].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[16].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X42Y100 [get_cells {GEN_PUF[16].PUF/CARRY4_inst}]
set_property src_info {type:XDC file:3 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[16].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X42Y100 [get_cells {GEN_PUF[16].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[17].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[17].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[17].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[17].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[17].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X44Y100 [get_cells {GEN_PUF[17].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X46Y100 [get_cells -hierarchical -regexp {GEN_PUF\[18\]\.PUF/SRLC32E_inst_.*}]
set_property src_info {type:XDC file:3 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[18].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[18].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[18].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[18].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X46Y100 [get_cells {GEN_PUF[18].PUF/CARRY4_inst}]
set_property src_info {type:XDC file:3 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[18].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X46Y100 [get_cells {GEN_PUF[18].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[19].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[19].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[19].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[19].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[19].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X48Y100 [get_cells {GEN_PUF[19].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X50Y100 [get_cells -hierarchical -regexp {GEN_PUF\[20\]\.PUF/SRLC32E_inst_.*}]
set_property src_info {type:XDC file:3 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[20].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[20].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[20].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[20].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X50Y100 [get_cells {GEN_PUF[20].PUF/CARRY4_inst}]
set_property src_info {type:XDC file:3 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[20].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X50Y100 [get_cells {GEN_PUF[20].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[21].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[21].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[21].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[21].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[21].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X52Y100 [get_cells {GEN_PUF[21].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X54Y100 [get_cells -hierarchical -regexp {GEN_PUF\[22\]\.PUF/SRLC32E_inst_.*}]
set_property src_info {type:XDC file:3 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[22].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[22].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[22].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[22].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X54Y100 [get_cells {GEN_PUF[22].PUF/CARRY4_inst}]
set_property src_info {type:XDC file:3 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[22].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X54Y100 [get_cells {GEN_PUF[22].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[23].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[23].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[23].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[23].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[23].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X56Y100 [get_cells {GEN_PUF[23].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X58Y100 [get_cells -hierarchical -regexp {GEN_PUF\[24\]\.PUF/SRLC32E_inst_.*}]
set_property src_info {type:XDC file:3 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[24].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[24].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[24].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[24].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X58Y100 [get_cells {GEN_PUF[24].PUF/CARRY4_inst}]
set_property src_info {type:XDC file:3 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[24].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X58Y100 [get_cells {GEN_PUF[24].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[25].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[25].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[25].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[25].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[25].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X60Y100 [get_cells {GEN_PUF[25].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X62Y100 [get_cells -hierarchical -regexp {GEN_PUF\[26\]\.PUF/SRLC32E_inst_.*}]
set_property src_info {type:XDC file:3 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[26].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[26].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[26].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[26].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X62Y100 [get_cells {GEN_PUF[26].PUF/CARRY4_inst}]
set_property src_info {type:XDC file:3 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[26].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X62Y100 [get_cells {GEN_PUF[26].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[27].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[27].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[27].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[27].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[27].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y100 [get_cells {GEN_PUF[27].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X66Y100 [get_cells -hierarchical -regexp {GEN_PUF\[28\]\.PUF/SRLC32E_inst_.*}]
set_property src_info {type:XDC file:3 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[28].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[28].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[28].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[28].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X66Y100 [get_cells {GEN_PUF[28].PUF/CARRY4_inst}]
set_property src_info {type:XDC file:3 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[28].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X66Y100 [get_cells {GEN_PUF[28].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[29].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[29].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[29].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[29].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[29].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[30].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[30].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[30].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[30].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[30].PUF/FDCPE_inst}]
set_property src_info {type:XDC file:3 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {GEN_PUF[31].PUF/SRLC32E_inst_0}]
set_property src_info {type:XDC file:3 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {GEN_PUF[31].PUF/SRLC32E_inst_1}]
set_property src_info {type:XDC file:3 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {GEN_PUF[31].PUF/SRLC32E_inst_2}]
set_property src_info {type:XDC file:3 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {GEN_PUF[31].PUF/SRLC32E_inst_3}]
set_property src_info {type:XDC file:3 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {GEN_PUF[31].PUF/FDCPE_inst}]
